### PR TITLE
Issue 19 and 29

### PR DESCRIPTION
**Pull request by pingnomw**
- Issue 19 (added status box)
- Issue 29 (made error messages clearer)
- made the board side-by-side and removed &lt;ul&gt;

### CODE REVIEW

**Comment by haewon0128** [comment]
It says this branch has conflicts i think you need to fix it

**Review by amberm1647 — COMMENTED** [review]
line 43 of ApplicationControllers.java might have an issue with brackets for the else statement

I'm not entirely sure what the additions in the java files do but will trust that it works

Changes to the css and html file might break earlier changes but it's probably fine

**Comment by pingnomw** [comment]
> line 43 of ApplicationControllers.java might have an issue with brackets for the else statement

The entire if-else statement is commented out (between /* and */)

**Comment by pingnomw** [comment]
The changes to the java files are necessary to display error messages other than the generic one

**Comment by amberm1647** [comment]
never mind, I didn't see it was commented out
it should be good to merge, I wasn't able to test my html/css changes so i trust that yours work better than mine

**Pull request merged**
